### ISSUE TITLE
Hey there? Weird way of contacting, I know.

### ISSUE THREAD

**Issue by ritvik1512** [raichur/noc#1]
Hey Joshua,
Ritvik here. I was trying to contact you for a while, can you return back to me whenever you can? Got a lot to discuss.
I wasn't being able to connect to you by other means, hence this way.

See you soon.
P.S. This book by Daniel is great.

Ritvik

**Comment by raichur** [comment]
Dropped you an email.

**Comment by ritvik1512** [comment]
Got that. :+1:
